import { Pagination } from '@getcommunity/gcui/pagination';
import { Component, createSignal } from 'solid-js';

const PaginationExample: Component = () => {
  const [page, setPage] = createSignal<number>(1);
  return (
    <div id='pagination' class='flex flex-col gap-1 pb-24 pt-12'>
      <h2 class='text-3xl font-bold'>Pagination</h2>
      <p class='text-lg'>This section demonstrates pagination.</p>
      <div class='flex w-full flex-col items-center gap-2'>
        <Pagination
          count={10}
          page={page}
          setPage={setPage}
          styleType='fill'
          color='info'
          curve='none'
        />
        <Pagination
          count={10}
          page={page}
          setPage={setPage}
          styleType='fill'
          color='info'
          curve='default'
        />
        <Pagination
          count={10}
          page={page}
          setPage={setPage}
          styleType='fill'
          color='info'
          curve='small'
        />
        <Pagination
          count={10}
          page={page}
          setPage={setPage}
          styleType='fill'
          color='info'
          curve='medium'
        />
        <Pagination
          count={10}
          page={page}
          setPage={setPage}
          styleType='fill'
          color='info'
          curve='large'
        />
        <Pagination
          count={10}
          page={page}
          setPage={setPage}
          styleType='fill'
          color='info'
          curve='full'
        />
      </div>
      <div class='flex flex-row flex-wrap'>
        <div class='flex w-full flex-col items-center gap-2 lg:w-1/2'>
          <p class=''>Rounded</p>
          <Pagination count={10} page={page} setPage={setPage} />
          <Pagination count={10} page={page} setPage={setPage} styleType='fill' />
          <Pagination count={10} page={page} setPage={setPage} styleType='outline' />
          <Pagination count={10} page={page} setPage={setPage} color='info' />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='fill'
            color='info'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='outline'
            color='info'
          />
          <Pagination count={10} page={page} setPage={setPage} color='error' />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='fill'
            color='error'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='outline'
            color='error'
          />
          <Pagination count={10} page={page} setPage={setPage} color='warning' />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='fill'
            color='warning'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='outline'
            color='warning'
          />
          <Pagination count={10} page={page} setPage={setPage} color='success' />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='fill'
            color='success'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='outline'
            color='success'
          />
          <Pagination count={10} page={page} setPage={setPage} color='light' />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='fill'
            color='light'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='outline'
            color='light'
          />
          <Pagination count={10} page={page} setPage={setPage} color='dark' />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='fill'
            color='dark'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            styleType='outline'
            color='dark'
          />
        </div>
        <div class='flex w-full flex-col items-center gap-2 lg:w-1/2'>
          <p class=''>Squared</p>
          <Pagination count={10} page={page} setPage={setPage} curve='none' />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='fill'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='outline'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            color='info'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='fill'
            color='info'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='outline'
            color='info'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            color='error'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='fill'
            color='error'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='outline'
            color='error'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            color='warning'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='fill'
            color='warning'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='outline'
            color='warning'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            color='success'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='fill'
            color='success'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='outline'
            color='success'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            color='light'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='fill'
            color='light'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='outline'
            color='light'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            color='dark'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='fill'
            color='dark'
          />
          <Pagination
            count={10}
            page={page}
            setPage={setPage}
            curve='none'
            styleType='outline'
            color='dark'
          />
        </div>
      </div>
    </div>
  );
};

export default PaginationExample;
