// Numbers
// Float
export const DB_FLOAT_MAXLEN_STORED = 20;
// Integer
export const DB_INT_INTEGER_MAXLEN_STORED = 4294967295;
// Strings
export const DB_STR_16BIT_MAXLEN_INPUT = 16;
export const DB_STR_16BIT_MAXLEN_STORED = 408;
export const DB_STR_32BIT_MAXLEN_INPUT = 32;
export const DB_STR_32BIT_MAXLEN_STORED = 428;
export const DB_STR_64BIT_MAXLEN_INPUT = 64;
export const DB_STR_64BIT_MAXLEN_STORED = 472;
export const DB_STR_TINYTEXT_MAXLEN_INPUT = 255;
export const DB_STR_TINYTEXT_MAXLEN_STORED = 704;
export const DB_STR_SHORTTEXT_MAXLEN_INPUT = 1024;
export const DB_STR_SHORTTEXT_MAXLEN_STORED = 1752;
export const DB_STR_URLPATH_MAXLEN_INPUT = 2048;
export const DB_STR_URLPATH_MAXLEN_STORED = 3116;
export const DB_STR_DESC_MAXLEN_INPUT = 5000;
export const DB_STR_DESC_MAXLEN_STORED = 7040;
export const DB_STR_BLOB_MAXLEN_INPUT = 45000;
export const DB_STR_BLOB_MAXLEN_STORED = 65535;
export const DB_STR_LONGTEXT_MAXLEN_STORED = 4294967295;
// OBJECT CONSTANTS
// DATA BUCKET
export const DB_STR_BUCKET_NAME_MINLEN_INPUT = 3;
export const DB_STR_BUCKET_NAME_MAXLEN_INPUT = 63;
export const DB_STR_BUCKET_OBJECT_KEY_MAXLEN_INPUT = 1024;
export const DB_STR_BUCKET_OBJECT_PREFIX_MAXLEN_INPUT = 769;
export const DB_STR_BUCKET_OBJECT_NAME_MINLEN_INPUT = 3;
export const DB_STR_BUCKET_OBJECT_NAME_MAXLEN_INPUT = 255;
// IPADDRESS
export const DB_STR_IPADDRESS_MAXLEN_INPUT = 50;
// USERS
export const DB_STR_USER_PICTURE_DEFAULT =
  'https://www.gravatar.com/avatar/?d=identicon';
// GCFT
export const DB_INT_ALTITUDE_MAX = 1000;
